remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: neon
plugins:
- jekyll-remote-theme
- jekyll-include-cache
include: ["_pages"]

title: Nick Dirschel
logo: assets/images/dirschn.png
name: Nick Dirschel
description: A site to showcase some of the things about Nick Dirschel.
repository: "dirschn/dirschn.github.io"

atom_feed:
  hide: true

# Site Author
author:
  name             : "Nick Dirschel"
  avatar           : "/assets/images/nick-dirschel.jpg"
  bio              : "A full stack web developer with a focus on clean, maintainable code"
  location         : "MA, USA"
  email            : "dirschn@gmail.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dirschn.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dirschn"
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/dirschn/'

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dirschn"
